### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by BZAghalarov** [masslbs/Tennessine#93]
hi,
I tried to setup the project based on your guide in root README file.
After successful 
    - `nix develop`
    - `pnpm install`
commands, I couldn't run `pnpm build` command.

It throws expected `ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "build" not found` due to `pnpm build` command didn't mentioned inside the root directorie's `package.json` file.

As a workaround I tried to run the `pnpm build` command from `packages/frontend` folder and I got [other error](https://pastebin.com/PuK4RC3b) which is related with workspace/environment.

Could you guide what was wrong here?

PNPM version: 8.15.5
Node version: v18.18.0

Solution: [Add build command ](https://github.com/masslbs/Tennessine/pull/95)to root `package.json` file

**Comment by wanderer** [comment]
We have switched to deno now
